---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'




dependencies:
  ansible_core:
    package_pip: ansible-core==2.13.13
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
#    - cryptography
#    - netaddr
#    - pyyaml
#    - jmespath
#    - simplejson
#    - wheel
#    - ping
#    - openssh_cert
#    - openssh_keypair
#    - openssl_certificate_info
#    - openssl_certificate
#    - openssl_csr
#    - openssl_csr_info
#    - openssl_dhparam
#    - openssl_pkcs12
#    - openssl_privatekey
#    - openssl_privatekey_info
#    - openssl_publickey
#  system: bindep.txt

images:
  base_image:
    name: quay.io/ansible/ansible-runner:latest

